---
- name: Install telegraf
  include: "{{ ansible_os_family|lower }}/install.yml"

- debug:
    msg: "Telegraf will point to InfluxDB on {{ influxdb_remote_urls }}"

- name: Create telegraf config file
  template:
    src: telegraf.conf.j2
    dest: "{{ telegraf_conf_dir }}/telegraf.conf"
    owner: root
    group: root
    mode:  0644
  notify: Restart telegraf
  become: true

- name: Add telegraf user to additional groups
  user:
    name: telegraf
    groups: "{{ telegraf_additional_groups|join(',') }}"
    append: yes
  when: telegraf_additional_groups is defined
  ignore_errors: true
  become: true

- name: Create telegraf startup script environment vars file
  template:
    src: etc.default.telegraf.j2
    dest: /etc/default/telegraf
    owner: root
    group: root
    mode: 0644
  notify: Restart telegraf
  become: true

- name: Create telegraf logrotate config file
  template:
    src: telegraf.logrotate.j2
    dest: /etc/logrotate.d/telegraf
    owner: root
    group: root
    mode: 0644
  become: true

- name: Start telegraf
  service:
    name: telegraf
    enabled: yes
    state: started
  become: true
